# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DMLC
email: muli.cmu@gmail.com
description: > # this means to ignore newlines
  DMLC for Scalable and Reliable Machine Learning
url: "http://dmlc.ml"

# Build settings
kramdown: redcarpet
highlighter: pygments

redcarpet:
  extensions: ["fenced_code_blocks", "no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]


